


# ========== SERVER ==========
spring.application.name=IMS-Backend
server.port=8080

# ========== MySQL ==========
spring.datasource.url=jdbc:mysql://localhost:3306/ims_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=ims_user
spring.datasource.password=ims_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========== JPA / HIBERNATE ==========
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# ========== JWT ==========
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# ========== SEED DATA ==========
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ========== JPA EXTRAS ==========
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# ========== SPRING AI / GROQ ==========
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile